name: ReleaseBuild

on:
  push:
    branches: [ "master", "Engine-Update" ]
  pull_request:
    branches: [ "master", "Engine-Update" ]
  workflow_dispatch : 
    branches: [ "master", "Engine-Update" ]


env:
  SOLUTION_FILE_PATH: LambEngine.sln
  CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        run: msbuild /m ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}} /p:BuildInParallel=true
